version: 2

before:
  hooks:
    - go mod download
builds:
  - id: default
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s"
      - "-w"
      - "-X github.com/fmotalleb/go-tools/git.Version={{.Version}}"
      - "-X github.com/fmotalleb/go-tools/git.Commit={{.ShortCommit}}"
      - "-X github.com/fmotalleb/go-tools/git.Date={{.Date}}"
      - "-X github.com/fmotalleb/go-tools/git.Branch={{.Branch}}"

dockers_v2:
  - id: traceroute-exporter
    sbom: false
    platforms:
      - linux/amd64
      - linux/arm64
    images:
      - ghcr.io/fmotalleb/traceroute-exporter
    tags:
      - "latest"
      - "{{ .Major }}"
      - "{{ .Major }}.{{ .Minor }}"
      - "{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    labels:
      "org.opencontainers.image.description": "Junction"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
    ids:
      - default

release:
  github:
  name_template: "{{.Version}}"
  prerelease: auto
  mode: append
changelog:
  disable: true
